export const NIGERIAN_BANKS = [
  { code: '044', name: 'Access Bank' },
  { code: '011', name: 'First Bank of Nigeria' },
  { code: '058', name: 'Guaranty Trust Bank' },
  { code: '057', name: 'Zenith Bank' },
  { code: '033', name: 'United Bank For Africa' },
  { code: '030', name: 'Heritage Bank' },
  { code: '032', name: 'Union Bank of Nigeria' },
  { code: '035', name: 'Wema Bank' },
  { code: '050', name: 'Ecobank Nigeria' },
  { code: '070', name: 'Fidelity Bank' },
  { code: '082', name: 'Keystone Bank' },
  { code: '232', name: 'Sterling Bank' },
  { code: '215', name: 'Unity Bank' },
  { code: '999992', name: 'OPay Digital Services Limited (OPay)' },
  { code: '100004', name: 'Palmpay' },
  { code: '090267', name: 'Kuda Bank' },
];
